# Generated by Django 4.1.3 on 2023-01-14 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Категорія')),
            ],
        ),
        migrations.CreateModel(
            name='HairdrassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/&d/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('price', models.CharField(max_length=50, verbose_name='Ціна')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_hd.category')),
            ],
        ),
    ]
