# Generated by Django 4.1.3 on 2023-01-15 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HairdrassModel',
            new_name='HairdressModel',
        ),
    ]
