# Generated by Django 4.1.3 on 2023-01-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0002_rename_hairdrassmodel_hairdressmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_date', models.CharField(max_length=100, verbose_name='date')),
                ('blocked_time', models.CharField(max_length=100, verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='id Користувача')),
                ('time', models.CharField(max_length=100, verbose_name='Час')),
                ('service', models.CharField(max_length=100, verbose_name='Послуга')),
                ('service_id', models.CharField(max_length=200, verbose_name='id послуги')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Номер телефону')),
                ('where_location', models.CharField(max_length=50, verbose_name='Місце')),
                ('location', models.CharField(max_length=200, verbose_name='Адреса')),
                ('description', models.CharField(max_length=1000, verbose_name='Коментарій')),
                ('is_accepted', models.CharField(max_length=15, verbose_name='Підтаерджено')),
            ],
        ),
    ]
