# Generated by Django 4.1.3 on 2023-01-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0003_blockedmodel_notesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedmodel',
            name='blocked_date',
            field=models.CharField(max_length=100, verbose_name='Тільки дата'),
        ),
        migrations.AlterField(
            model_name='blockedmodel',
            name='blocked_time',
            field=models.CharField(max_length=100, verbose_name='Дата і час'),
        ),
    ]
