# Generated by Django 4.1.3 on 2023-01-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0004_alter_blockedmodel_blocked_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hairdressmodel',
            old_name='title',
            new_name='hairdress',
        ),
    ]
