# Generated by Django 4.1.3 on 2023-01-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0005_rename_title_hairdressmodel_hairdress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesmodel',
            name='service',
            field=models.CharField(max_length=100, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='notesmodel',
            name='service_id',
            field=models.CharField(max_length=200, verbose_name='Послуги'),
        ),
    ]
