# Generated by Django 4.1.3 on 2023-01-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0006_alter_notesmodel_service_alter_notesmodel_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairdressmodel',
            name='price',
        ),
    ]
