# Generated by Django 4.1.3 on 2023-01-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0007_remove_hairdressmodel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('email', models.CharField(max_length=200, verbose_name='E-Mail')),
                ('review_text', models.CharField(max_length=1000, verbose_name='Відгук')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='hairdressmodel',
            options={'verbose_name': 'Зачіска', 'verbose_name_plural': 'Зачіски'},
        ),
        migrations.AlterModelOptions(
            name='notesmodel',
            options={'verbose_name': 'Запис', 'verbose_name_plural': 'Записи'},
        ),
        migrations.CreateModel(
            name='ReviewIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='IP-адресв')),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_hd.reviewsmodel', verbose_name='Відгук')),
            ],
        ),
    ]
