# Generated by Django 4.1.3 on 2023-01-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0008_reviewsmodel_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsmodel',
            name='ip',
            field=models.CharField(blank=True, max_length=100, verbose_name='IP-адреса'),
        ),
        migrations.DeleteModel(
            name='ReviewIP',
        ),
    ]
