# Generated by Django 4.1.3 on 2023-01-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0009_reviewsmodel_ip_delete_reviewip'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairdressmodel',
            name='time_spend',
            field=models.TextField(blank=True, verbose_name='Час, який витрачається на послугу'),
        ),
        migrations.AlterField(
            model_name='hairdressmodel',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='reviewsmodel',
            name='ip',
            field=models.CharField(max_length=100, verbose_name='IP-адреса'),
        ),
    ]
