# Generated by Django 4.1.3 on 2023-01-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_hd', '0010_hairdressmodel_time_spend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairdressmodel',
            name='time_spend',
            field=models.CharField(blank=True, max_length=50, verbose_name='Час, який витрачається на послугу'),
        ),
    ]
